# Generated by Django 6.0.5 on 2026-05-25 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la marca', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Marca de Accesorio',
                'verbose_name_plural': 'Marcas de Accesorios',
            },
        ),
        migrations.CreateModel(
            name='CardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_card_id', models.CharField(help_text='ID único de la carta en la API del TCG correspondiente', max_length=100)),
                ('game_type', models.CharField(choices=[('YGO', 'Yu-gi-oh!'), ('PKM', 'Pokémon TCG'), ('DGM', 'Digimon TCG'), ('CFG', 'Cardfight!! Vanguard'), ('MTG', 'Magic The Gathering'), ('RB', 'Riftbound TCG (Riot)')], help_text='Selecciona el TCG al que pertenece la carta', max_length=3)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en tienda')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta de la carta en MXN', max_digits=10)),
                ('rarity', models.CharField(default='Common', help_text='Rareza de la carta', max_length=50)),
                ('condition', models.CharField(choices=[('M', 'Mint'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='M', help_text='Estado físico de la carta', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro la carta')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la carta')),
            ],
            options={
                'verbose_name': 'Carta en Inventario',
                'verbose_name_plural': 'Cartas en Inventario',
                'ordering': ['-created_at'],
                'unique_together': {('external_card_id', 'game_type', 'condition', 'rarity')},
            },
        ),
        migrations.CreateModel(
            name='SealedProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('YGO', 'Yu-gi-oh!'), ('PKM', 'Pokémon TCG'), ('DGM', 'Digimon TCG'), ('CFG', 'Cardfight!! Vanguard'), ('MTG', 'Magic The Gathering'), ('RB', 'Riftbound TCG (Riot)')], help_text='Selecciona el TCG al que pertenece el producto', max_length=3)),
                ('name', models.CharField(help_text='Categoría de producto (ej: Booster Box, Mega Tin, Elite Trainer Box)', max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Producto Sellado',
                'verbose_name_plural': 'Categorías de Productos Sellados',
                'unique_together': {('game_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccesoryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Matte Black Sleeves - 100 ct)', max_length=200)),
                ('accessory_type', models.CharField(choices=[('SLV', 'Micas / Fundas'), ('DBX', 'Porta decks'), ('MAT', 'Playmats'), ('BND', 'Carpetas / Album'), ('DIC', 'Dados / Contadores'), ('PRT', 'Protectores rígidos (Toploaders/One-Touch)'), ('CNS', 'Monedas / Fichas')], help_text='Tipo de accesorio de juego', max_length=3)),
                ('size', models.CharField(choices=[('STD', 'Standard Size (Pokémon, Magic, Lorcana)'), ('JPN', 'Japanese / Small Size (Yu-Gi-Oh!, Vanguard)'), ('UNI', 'Universal / No Aplica')], default='UNI', help_text='Tamaño físico del accesorio', max_length=3)),
                ('color_design', models.CharField(blank=True, help_text='Color o arte impreso', max_length=100, null=True)),
                ('upc_code', models.CharField(blank=True, help_text='Código de barras de fábrica', max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Selecciona la marca del accesorio', on_delete=django.db.models.deletion.PROTECT, related_name='accessories', to='inventory.accessorybrand')),
            ],
            options={
                'verbose_name': 'Accesorio',
                'verbose_name_plural': 'Accesorios',
                'unique_together': {('name', 'brand', 'accessory_type', 'size')},
            },
        ),
        migrations.CreateModel(
            name='SealedProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del producto (ej: Justice Hunters, Phantasmal flames)', max_length=360)),
                ('upc_code', models.CharField(blank=True, help_text='Código de barras del producto', max_length=50, null=True)),
                ('external_product_id', models.CharField(blank=True, help_text='ID del producto en APIs de distribuidores o catálogos externos', max_length=100, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en tienda')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta en MXN', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.sealedproductcategory')),
            ],
            options={
                'verbose_name': 'Producto Sellado',
                'verbose_name_plural': 'Productos Sellados',
                'unique_together': {('name', 'category')},
            },
        ),
    ]
